require: build/test/setup.js
watch-files:
  - build/**/*
ignore:
  - build/test/unit/**/*
  - build/test/e2e/**/*
  - test/,src/,.garden
reporter: spec
timeout: 180000
exit: true
spec:
  - build/test/integ/**/*.js
